For comments
ssedinkin/perl_oop pull request #5
Opened 2017-02-22 13:29 UTC by ssedinkin

2017-02-22 15:05 UTC, timurn commented on Crew.pm
> +  elsif ( $field eq 'Rank' and $value =~ /^\w+$/ ) {
Как бы все эти развестистые условия преврать в один хеш и одну строчку проверки?

2017-02-22 20:03 UTC, ssedinkin commented on Crew.pm
> +  elsif ( $field eq 'Rank' and $value =~ /^\w+$/ ) {
Судя по описанию задания, понял, что нужны только кириллические имена. С ними диапазон [а-яА-ЯёЁ]+ не работает. Если по заданию не обязательны только кириллические символы в ФИО, то запись будет такой:
if ( $field eq 'Name' and $value =~ /^([\w]+)\s([\w]+)\s([\w]+)$/ ) {
￼ Возможно, в самом начале потребуются
use locale;
use utf8;

2017-02-27 12:58 UTC, timurn requested changes

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +  if ( $field eq 'Name' and $value =~ /^([йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮёЁ]+)\s([йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮёЁ]+)\s([йцукенгшщзх
А диапазоны [А-Яа-я] чем не устраивают?

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +        *{$AUTOLOAD} = sub {
Я правильно понимаю, что при каждом вызове сеттера ты заново его генерируешь?

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +
Приведи в порядок отступы по всему файлу. Наш стандарт - четыре пробела.

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +	my($class) = @_;
Как правило, конструктор должен уметь не только создать пустой объект, но и заполнить его.

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +        Name => '',
Имена в Perl, как правило, не именуются с заглавной буквы, если нет на это явных серьёзных оснований.

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +    if ($AUTOLOAD =~ /::set_(\w+)$/ and grep $1 eq $_, @elements) {
По условиям задания геттеры и сеттеры дожны иметь одно и то же имя.

2017-02-27 12:58 UTC, timurn commented on Crew.pm
> +  if ( $field eq 'Name' and $value =~ /^([йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮёЁ]+)\s([йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮёЁ]+)\s([йцукенгшщзх
Не понял, почему не работает [а-яА-ЯёЁ]+?

2017-03-02 22:03 UTC, closed without merging